### ISSUE TITLE
Issue while running script.

### ISSUE THREAD

**Issue by OmerFarukOruc** [ericlincn/diablo-immortal-bot#1]
ModuleNotFoundError: No module named 'HookKeyboard'. Also when i comment the lines i get error of;
"OSError: Failed to read __images/healthBarLeft.png because file is missing, has improper permissions, or is an unsupported or invalid format"

Looks like there isn't bot images folder available.  Thanks for now.

**Comment by ghost** [comment]
Any success about this images?
